###
POST http://localhost:5000/api/v2/series/serie HTTP/1.1
Content-Type: application/json

{
  "serie": "The Big Bang Theory",
  "number_seasons": 5,
  "original_lenguage":"english",
  "features_seasons":[{"season_number":1, "season_name": "season 1","premier_date":"01-03-2005",
  "cast":["Sheldon","Leonar","Penny", "Feid"],
  "episodes":[{"episode_name":"sheldon bromea","time_duration":20}]}]
}
### obtener todos
GET http://localhost:5000/api/v2/series HTTP/1.1
### obtener por id
GET http://localhost:5000/api/v2/series/623c71c6a61cca647a9b3e36 HTTP/1.1
### obtener por nombre de actor
GET http://localhost:5000/api/v2/series/623c71c6a61cca647a9b3e36 HTTP/1.1
###
PUT http://localhost:5000/api/v2/series/ HTTP/1.1
Content-Type: application/json

{
  "number_seasons": 98
}
###
DELETE http://localhost:5000/api/v2/series/62438ff574ebfa16d569c2ce HTTP/1.1

### obtener serie donde actue un actor especifico.
GET http://localhost:5000/api/v2/series/actor/Feid HTTP/1.1

### obtener con serie por fecha de estreno.
GET http://localhost:5000/api/v2/series/fecha/01-03-2004 HTTP/1.1

